---
- name: Ensure PostgreSQL is ready
  meta: flush_handlers

- name: Install PostGIS
  apt:
    name: "postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}"
    state: present
    update_cache: yes

- name: Install PostGIS extensions
  apt:
    name:
      - postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}-scripts
      - postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}
    state: present

- name: Enable PostGIS extension
  postgresql_db:
    name: "{{ postgresql_database | default('geo_db') }}"
    state: present
  become_user: postgres
  become: yes

- name: Create PostGIS extension
  postgresql_ext:
    name: postgis
    db: "{{ postgresql_database | default('geo_db') }}"
    state: present
  become_user: postgres
  become: yes

- name: Create PostGIS Topology extension
  postgresql_ext:
    name: postgis_topology
    db: "{{ postgresql_database | default('geo_db') }}"
    state: present
  become_user: postgres
  become: yes 