---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create cache directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data
  with_items:
    - /var/cache/nginx/vector_cache
    - /var/cache/nginx/osm_cache

- name: Copy main Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: restart nginx

- name: Copy site configuration
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    mode: '0644'
  notify: restart nginx

- name: Create web root directory
  file:
    path: /var/www/html
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data

- name: Copy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
    owner: www-data
    group: www-data
  notify: restart nginx

- name: Enable and start Nginx
  service:
    name: nginx
    state: started
    enabled: yes 